### ISSUE TITLE
Targeting S+ (version 31 and above) 

### ISSUE THREAD

**Issue by nafanz** [depler/transmission-android#2]
Redmi Note 9 Pro
Android 12 SKQ1.211019.001
MIUI Global 13.0.1

The application crashes on startup, video is attached.
I connected my phone to a PC and tried to collect logs through Android studio, I'm not a developer - I hope there is useful data there.

[log.txt](https://github.com/depler/transmission-android/files/10684534/log.txt)

https://user-images.githubusercontent.com/36957143/217507277-f496be58-8d8f-45a7-8a1c-8c340f252b01.mp4

**Comment by depler** [comment]
Hi! I'll take a look at it later, don't how much time now

**Comment by depler** [comment]
Fixed and updated up to release 4.0.0 version, enjoy: https://github.com/depler/transmission-android/releases/tag/20230209

**Comment by nafanz** [comment]
After starting the application does not open, only this message appears.  There is permission to access media files.  If possible, I'll try to add logs one of these days.![Screenshot_2023-02-09-22-32-51-887_com.miui.home.jpg](https://user-images.githubusercontent.com/36957143/217893261-1c925dc0-da16-4775-bf3b-94c8eb221283.jpg)

**Comment by nafanz** [comment]
After starting the application does not open, only this message appears.  There is permission to access media files.  If possible, I'll try to add logs one of these days.![Screenshot_2023-02-09-22-37-23-630_com.miui.home.jpg](https://user-images.githubusercontent.com/36957143/217893746-56c0ecee-e48d-439e-8cef-b5d36e9290a4.jpg)

**Comment by depler** [comment]
If you see this screen - then everything works just fine. Transmission is a background service, it has no build-in interface.

Now you need some third party client for transmission server, for example this one: https://play.google.com/store/apps/details?id=com.sleroy.transmissionic. Just install it and connect to localhost on port 9091.
