### ISSUE TITLE
F-Droid inclusion? 

### ISSUE THREAD

**Issue by Pentaphon** [depler/transmission-android#4]
Any chance of putting this app on F-Droid? Or have some way to update it?

https://f-droid.org/

**Comment by depler** [comment]
Don't have such plans right now. If anyone wants to add it to Fdroid store - I will support it. Just don't have much time.

**Comment by IzzySoft** [comment]
Now that the license question has been solved (thanks to @depler for merging!), Transmission will become [available in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.depler.transmission) with the next sync at around 6 pm UTC. @Pentaphon you can now go ahead opening a [Request for Packaging](https://gitlab.com/fdroid/rfp/-/issues/) with F-Droid: with the license added, the app should now meet the inclusion criteria (at least as far as I can see; I'm not a C# developer, or an Android developer at that – so I cannot guarantee all build criteria are met).

**Comment by Pentaphon** [comment]
> Transmission will become [available in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.depler.transmission) with the next sync at around 6 pm UTC

That's pretty much all I wanted: at least one way to keep this updated. I'm not as interested in F-droid anymore since izzydroid has proven to be faster at getting me updated. If somebody else wants to have it on F-droid, they can do it. Thanks @IzzySoft

**Comment by IzzySoft** [comment]
Haha, thought so, @Pentaphon – so all fine from my end (to the defense of F-Droid: my updates can be faster as I just grab the APK and do not build from source myself, so there's no "build cycle" to wait for). And good to know @depler is not opposed to a listing at F-Droid.org, so if someone opens an RFP there they can link to that. Until then, Transmission is welcome to stay with my repo.

@depler in case you wonder: your app will usually be updated in my repo within 24h of your creating a new tag and attaching the APK to it. Should that fail for some reason (happens rarely but does e.g. when tags are misnamed or `versionCode` "breaks"), feel free to drop me a note (or others like @Pentaphon will do, which is also fine) and I'll investigate. Thanks a lot again!

**Comment by Pentaphon** [comment]
> my updates can be faster as I just grab the APK and do not build from source myself, so there's no "build cycle" to wait for).

Yeah I'm aware of that. Plus you seem to scan for malware. That's enough for me. As long as a github project has either your repo or F-droid, that's enough for most projects, I'd say. Somebody will get this project on f-droid when it becomes more popular.
